### ISSUE TITLE
Can you expand docs to break down options?

### ISSUE THREAD

**Issue by khrome83** [xpyxel/dash#22]
**Is your feature request related to a problem? Please describe.**

The code show more options than the README.md explains. While there are comments, I don't really understand what some of these do being new to LRU cache. 
```
export interface CacheOptions {
  /**
   * The max number of items the cache can store (defaults to 10,000)
   */
  limit?: number;
  /**
   * Wether to serialize json-parsable data
   */
  serialize?: boolean;
  /**
   * Use a logical limiting system
   */
  logical?: boolean;
  /**
   * The threshold in which the cache will resize its limit in logical mode
   */
  threshold?: number;
  /**
   * The amount the cache will increase its limit after the threshold is hit
   */
  increase?: number;
}
```
**Describe the solution you'd like**

Can you explain how these work in the README.md

**Comment by xpyxel** [comment]
I'll expand the documentation in the README soon-ish, been busy so haven't had time to work on the library
